import Nav from './auth/Nav'
import QueryWrapper from './auth/QueryWrapper'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-48 xl:mx-96 font-sans bg-gray-800`}>
        <QueryWrapper>
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  )
}
